### ISSUE TITLE
# 88 ideas to code.

### ISSUE THREAD

**Issue by thelastinuit** [TheClowder/88catz#1]
Let's code 88 simple ideas in Go and Elixir which I believe will be current languages to code.
The ideas no need to be complex the only rule is: it has to be done one per day.
It will start on a prime day which will be Aug 17th, 2017 to end on another prime day
Nov 13th, 2017.
The repertoire will be katas from Code Wars of level 6-8 (to keep it simple)

**Comment by mayra-cabrera** [comment]
wUUUU  I'm definitely in! ... _you know_
