### ISSUE TITLE
Can I playz?

### ISSUE THREAD

**Issue by MrOutis** [TheClowder/88catz#2]
![](https://media.giphy.com/media/Hcw7rjsIsHcmk/giphy.gif)

**Comment by mayra-cabrera** [comment]
Sure! ... Rules will be updated soon, in the mean time #1 ![](https://media.giphy.com/media/JIX9t2j0ZTN9S/giphy-downsized.gif)

**Comment by thelastinuit** [comment]
@MrOutis ABUELA DE BATMAN!

**Comment by thelastinuit** [comment]
close since everyone is welcome
